### ISSUE TITLE
React 15.1: Uncaught Invariant Violation with Select component

### ISSUE THREAD

**Issue by jasrusable** [hallister/semantic-react#120] opened 2016-07-13 16:37 UTC
Hello, I am getting

    Uncaught Invariant Violation: getNodeFromInstance: Invalid argument.

in the browser console when using the Select component and the Select does not function correctly.

I am using Chromium Version 51.0.2704.79 Built on 8.4, running on Debian 8.5 (64-bit)
with semantic-react 8d65a15

Here is my component:
```
class MySelect extends React.Component {
  constructor() {
    super()
    this.state = {
      active: false,
    }
  }

  render() {
    const { active } = this.state
    return (
      <Select
        selection
        active={active}
        placeholder="Hi"
        onClick={() => this.setState({ active: true })}
        onRequestClose={() => this.setState({ active: false })}
        onSelectChange={val => console.log(val)}
      >
        <Option key="a" value="a">a</Option>
        <Option key="b" value="b">b</Option>
      </Select>
    )
  }
}
```

This is what I get upon refreshing (and force refreshing) the page with MySelect mounted:
![image](https://cloud.githubusercontent.com/assets/3955714/16811447/b2155caa-4928-11e6-8ecd-3bfd190bf651.png)

**Comment by asvetliakov** [comment] 2016-07-13 16:38
Sorry about that! Will check & fix today

**Comment by jasrusable** [comment] 2016-07-13 16:52
Oops! I should have checked my dependency versions.
This is not an issue on the latest version of React 15.2.1, but is present on 15.1.0, so I have solved this by updating to the latest React :)

**Comment by asvetliakov** [comment] 2016-07-13 16:54
Ok, thank you for information, i'll check with 15.1.0

**Comment by asvetliakov** [comment] 2016-07-13 17:57
Can't reproduce on react 15.1.0 . Not sure why you got this error.

**Comment by jasrusable** [comment] 2016-07-14 14:45
Thats odd, sorry about that. I suppose this can be closed then, I no longer have an issue :) Thanks for your work!

**Comment by asvetliakov** [comment] 2016-07-14 15:08
Ok, closing, thanks!

**Closed by asvetliakov** 2016-07-14 15:08 UTC
