### ISSUE TITLE
[Bug] Input component doesn't passing other props to html input element

### ISSUE THREAD

**Issue by tomitrescak** [hallister/semantic-react#67] opened 2016-03-31 01:04 UTC
When I use "ref" with an input, it is not possible to use it with React.

**Comment by tomitrescak** [comment] 2016-03-31 01:39
I checked and refs and ids are rendered in the parent div, not in the child input. That is not a correct behaviour. On top, this makes accessing refs a bit problematic. Even if you render ref correctly, you need to access ref in the child component not the parent one. It's a bit of a pickle.

**Comment by tomitrescak** [comment] 2016-03-31 01:49
I guess, the easiest way to do this is to expose property "value" on the Input component that returns value of the input. I can do a PR, but I'm not sure how you compile jsx into the lib and dist directory.

**Comment by asvetliakov** [comment] 2016-03-31 02:05
Confirmed. Another problem, it's passing ...other props to <div> wrapped to input not the input itself, so standard onChange, value, .etc won't work.
If you need ref to <input> element itself, we can make something like it:
```jsx
<Input ref={ref => this.input = ref} />
///somewhere in handler/callback:
this.input.inputElement.value; // original HTML input element
```
but i'm not sure if it's a good way to do things, so question: Do you need just working <Input> or you must use ref to the HTML input somehow ?

**Comment by tomitrescak** [comment] 2016-03-31 02:13
I think that the proper way would be to expose all the needed functionality on Input itself. Anthing else would be and look quite hacky.

e.g.

```
<Input ref="my" onChange={this.props.func}" />

// in code of Input

get value() {
    return this.props.input.value;
}

// and

<input
                onChange={this.props.onChange}
                key="input"
                ref="input"
                name={this.props.name}
                placeholder={this.props.placeholder} />
```

What do you think ?

**Comment by asvetliakov** [comment] 2016-03-31 02:21
So you want to work with input in uncontrolled component way? I wanted to turn simple components into functional style :disappointed:

**Comment by tomitrescak** [comment] 2016-03-31 02:24
Hmm, makes sense. Well, I leave it up to you then ;) What I proposed was simple, yet carried its own problems as you mentioned.

**Comment by asvetliakov** [comment] 2016-03-31 02:29
I think most react devs are using some kind of state container (redux, flux), so controlled API are on top priority. So just passing onChange, onBlur and standard callbacks to input element is fine in most cases. Even if ref or value will not be available in ```<Input>``` itself, you can easily to do it byself, by wrapping component, something like it:

```jsx
class MyInput extends React.Component {
  constructor() {
    ...
    this.state = {
      inputVal: ''
   }
   onInputChange(val) {
      this.setState({ inputVal: val });
  }
  render() {
     return (<Input onChange={this.onInputChange.bind(this)} value={this.state.inputVal}>
  }
 // if you really need imperative API
  getMyValue() {
     return this.state.inputVal;
  }
}
```

**Comment by Asgator** [comment] 2016-03-31 05:26
Hm, i am think it not work, because.
```
let inputHTML = (
            <input
                key="input"
                name={this.props.name}
                placeholder={this.props.placeholder} />
        );
```

https://github.com/hallister/semantic-react/blob/master/src/components/elements/input/input.jsx

**Comment by asvetliakov** [comment] 2016-03-31 05:28
Yes, it won't work now, that's why i marked it as bug

**Comment by asvetliakov** [comment] 2016-04-09 19:50
New ```<Input>``` was landed by https://github.com/hallister/semantic-react/pull/71, see new examples

**Closed by asvetliakov** 2016-04-09 19:50 UTC
